version: 2

models:

  - name: dim_listings_cleansed
    description: Cleansed Airbnb listings data

    columns:

      - name: listing_id
        description: Primary key for the listings
        tests:
          - unique
          - not_null

      - name: host_id
        description: host id that references the host table
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id

      - name: room_type
        description: Type of appartment/room
        tests:
          - accepted_values:
              values: [
                  'Entire home/apt',
                  'Private room',
                  'Shared room',
                  'Hotel room'
              ]

      - name: minimum_nights
        tests:
          - positive_value
