version: 2

models:

  - name: dim_listings_cleansed
    description: Cleansed Airbnb listings data
    columns:
      - name: listing_id
        description: Primary key for the listings
        tests:
          - unique
          - not_null
      - name: host_id
        description: host id that references the host table
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id
      - name: room_type
        description: Type of appartment/room
        tests:
          - accepted_values:
              values: [
                  'Entire home/apt',
                  'Private room',
                  'Shared room',
                  'Hotel room'
              ]
      - name: minimum_nights
        description: ' {{doc ("dim_listing_cleansed__minimum_nights") }}'
        tests:
          - positive_value

  - name: dim_hosts_cleansed
    description: Cleansed Airbnb hosts data
    columns:
      - name: host_id
        description: The id of the host. This is the primary key.
        tests:
          - not_null
          - unique
      - name: host_name
        description: The name of the host
        tests:
          - not_null
      - name: is_superhost
        description: Boolean to define if the host is superhost
        tests:
          - accepted_values:
              values: [ 't', 'f' ]

  - name: dim_listings_with_hosts
    description: table that joins cleaned versions of listings and hosts
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source('airbnb', 'listings')
    columns:
      - name: price
        tests:
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .99
              min_value: 50
              max_value: 500
          - dbt_expectations.expect_column_max_to_be_between:
              max_value: 5000
              config:
                severity: warn
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number

