version: 2

sources:
  - name: airbnb
    schema: raw
    tables:
      - name: listings
        identifier: raw_listings
        test:
          - dbt_expectations.expect_column_distinct_count_to_equal:
              value: 4

      - name: hosts
        identifier: raw_hosts

      - name: reviews
        identifier: raw_reviews
        loaded_at_field: date
        freshness:
          warn_after: {count: 36, period: hour}
          error_after: {count: 94, period: hour}