version: 2

sources:
  - name: airbnb
    schema: raw
    tables:

      - name: listings
        identifier: raw_listings
        columns:
          - name: room_type
            description: Possible roomtypes that can be rented by an Airbnb user.
            tests:
              - dbt_expectations.expect_column_distinct_count_to_equal:
                  value: 4
          - name: price
            description: Price of the listing in USD.
            tests:
              - dbt_expectations.expect_column_values_to_match_regex:
                  regex: "\\\\$[0-9][0-9\\\\.]+$"

      - name: hosts
        identifier: raw_hosts

      - name: reviews
        identifier: raw_reviews
        loaded_at_field: date
        freshness:
          warn_after: {count: 36, period: hour}
          error_after: {count: 94, period: hour}